name: Trigger auto deployment for gamegen-api

on:
  push:
    branches: 
      [ main ]
    paths:
    - '**'
    - '.github/workflows/gamegen-api-AutoDeployTrigger-93e6e1d6-b905-435c-bd73-bc69704f7fd7.yml'

  workflow_dispatch:      

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
        
      - name: Check Python Version  # ⬅️ Add this step
        run: python --version

      - name: Set up Python
        uses: actions/setup-python@v3
        with:
          python-version: "3.9"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Run unit tests
        env:
            CI: true
        run: python -m unittest discover test  # Use unittest

  build-and-deploy:
    needs: test  # Ensures tests must pass before deploying
    runs-on: ubuntu-latest
    permissions: 
      id-token: write
      contents: read

    steps:
      - name: Checkout to the branch
        uses: actions/checkout@v2

      - name: Azure Login
        uses: azure/login@v1
        with:
          client-id: ${{ secrets.GAMEGENAPI_AZURE_CLIENT_ID }}
          tenant-id: ${{ secrets.GAMEGENAPI_AZURE_TENANT_ID }}
          subscription-id: ${{ secrets.GAMEGENAPI_AZURE_SUBSCRIPTION_ID }}

      - name: Build and push container image to registry
        uses: azure/container-apps-deploy-action@v2
        with:
          appSourcePath: ${{ github.workspace }}
          _dockerfilePathKey_: _dockerfilePath_
          registryUrl: gamegenacr.azurecr.io
          registryUsername: ${{ secrets.GAMEGENAPI_REGISTRY_USERNAME }}
          registryPassword: ${{ secrets.GAMEGENAPI_REGISTRY_PASSWORD }}
          containerAppName: gamegen-api
          resourceGroup: gamegen-rg
          imageToBuild: gamegenacr.azurecr.io/gamegen-api:${{ github.sha }}
          _buildArgumentsKey_: |
            _buildArgumentsValues_
